DoorGodWeb/DoorGodWeb/Controllers/CarPassportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoorGodWeb.Models;
using DoorGodWeb.Abstract;

namespace DoorGodWeb.Controllers
{
    public class CarPassportController : Controller
    {
        private ICardService cardService;

        public CarPassportController(ICardService cardService)
        {
            this.cardService = cardService;
        }

        // GET: CarPassport
        public ViewResult Add()
        {
            ViewBag.CarType = DoorGodConst.GetCarPassportType();
            return View(new CarPassport());
        }

        [HttpPost]
        public ActionResult Add(CarPassport carPassport)
        {
            if (ModelState.IsValid)
            {
                //TODO: Implement call WebService function.                
                string result = cardService.AddCarPassport(carPassport);               

                TempData["message"] = result;
                return RedirectToAction("Add");
            }
            else
            {
                return View(carPassport);
            }
        }

        public ViewResult Delete()
        {
            ViewBag.CarType = DoorGodConst.GetCarPassportType();
            return View(new CarPassport());
        }

        [HttpPost]
        public ActionResult Delete(CarPassport carPassport)
        {
            string result = cardService.DeleteCarPassport(carPassport);
            TempData["message"] = result;
            return View(carPassport);
        }

        public ViewResult ClearAll()
        {
            ViewBag.CarType = DoorGodConst.GetCarPassportType();
            return View();
        }

        [HttpPost]
        public ActionResult ClearAll(string setNo, string carType)
        {
            string result = cardService.ClearAllCarPassport(setNo, carType);
            TempData["message"] = result;
            return View();
        }
    }
}

DoorGodWeb/DoorGodWeb/Controllers/CreateCardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoorGodWeb.Models;
using System.Diagnostics;
using DoorGodWeb.Core;
using DoorGodWeb.Abstract;

namespace DoorGodWeb.Controllers
{
    public class CreateCardController : Controller
    {
        private ICardService cardService;
        
        public CreateCardController(ICardService cardService)
        {
            this.cardService = cardService;
        }        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            //員工身分需下拉式選單
            ViewBag.empRoleListItem = DoorGodConst.GetEmpRoleListItem();
            return View(new EmpInfo());
        }


        [HttpPost]
        public ActionResult Create(EmpInfo emp)
        {
            ViewBag.empRoleListItem = DoorGodConst.GetEmpRoleListItem();

            try
            {
                if (ModelState.IsValid)
                {
                    TempData["message"] = cardService.SetEmp(emp);
                    return View();
                }
                return View(emp);
            }
            catch (Exception ex)
            {
                //TODO WriteLog
                Debug.WriteLine(ex.Message);
                TempData["message"] = ex.Message;
                return View();
            }
            
        }             

        public ActionResult AddCard()
        {
            ViewBag.cardStateListItem = DoorGodConst.GetCardStateListItem();

            return View(new AddCardInfo());
        }
        [HttpPost]
        public ActionResult AddCard(AddCardInfo addCardInfo)
        {

            try
            {
                ViewBag.cardStateListItem = DoorGodConst.GetCardStateListItem();

                if (ModelState.IsValid)
                {
                    TempData["message"] = cardService.SetEmpCard( addCardInfo.EmpNo, addCardInfo.CardNo, addCardInfo.CardState);
                    return View();
                }
                return View(addCardInfo);
            }
            catch (Exception ex)
            {
                //TODO WriteLog
                Debug.WriteLine(ex.Message);
                TempData["message"] = ex.Message;
                return View();
            }
        }

    }
}

DoorGodWeb/DoorGodWeb/Controllers/TempCardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoorGodWeb.Abstract;
using DoorGodWeb.Models;

namespace DoorGodWeb.Controllers
{
    public class TempCardController : Controller
    {
        private ICardService cardService;

        public TempCardController(ICardService cardService)
        {
            this.cardService = cardService;
        }

        // GET: TempCard
        public ActionResult Index()
        {
            ViewBag.CardState = DoorGodConst.GetEmpTempCardState();
            return View();
        }

        [HttpPost]
        public ViewResult Index(string empNo, string cardNo, string cardState)
        {
            ViewBag.CardState = DoorGodConst.GetEmpTempCardState();

            string result = cardService.SetEmpTempCard(empNo, cardNo, cardState);
            
            TempData["message"] = result;
            return View();

        }
               
    }
}

DoorGodWeb/DoorGodWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DoorGod</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    @*<span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>*@
                </button>
                @Html.ActionLink("DoorGod", "Create", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("新增", "Create", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            員工卡<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("新增異動員工", "Create", "CreateCard")</li>
                            <li>@Html.ActionLink("刪除人員", "Delete", "CreateCard")</li>
                            <li>@Html.ActionLink("設定員工卡片", "AddCard", "CreateCard")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            停車證<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("新增停車證人員", "Add", "CarPassport")</li>
                            <li>@Html.ActionLink("刪除停車證人員", "Delete", "CarPassport")</li>
                            <li>@Html.ActionLink("清除期別所有人員", "ClearAll", "CarPassport")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            臨時卡<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("員工臨時卡", "Index", "TempCard")</li>                            
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 DoorGod</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>